<?xml version="1.0"?>

<!DOCTYPE log [
<!ELEMENT log (Visit*, Page+ ,Visitor+)>
<!ELEMENT Visit (vdate,vtime)>
<!ELEMENT vdate (#PCDATA)>
<!ELEMENT vtime (#PCDATA)>
<!ATTLIST Visit tid CDATA #REQUIRED>
<!ATTLIST Visit pid CDATA #REQUIRED>
<!ATTLIST Visit vid CDATA #REQUIRED>
<!ELEMENT Page (url)>
<!ATTLIST Page pid CDATA #REQUIRED>
<!ELEMENT url (#PCDATA)>
<!ELEMENT Visitor (ip)>
<!ATTLIST Visitor vid CDATA #REQUIRED>
<!ELEMENT ip (#PCDATA)>
]>

<log>
  <Page pid="100">
    <url>http://artificium.us/lessons/l101.html</url>
  </Page>
  <Page pid="200">
    <url>http://articificum.us/courses/cs1100.html</url>
  </Page>
  <Page pid="300">
    <url>https://www.google.com/</url>
  </Page>
  <Page pid="400">
    <url>https://www.yahoo.com/</url>
  </Page>
  <Page pid="500">
    <url>https://www.kinderjoy.com/</url>
  </Page>
  <Page pid="600">
    <url>https://www.wonderland.com/</url>
  </Page>
  <Visit tid="1" pid="100" vid="101">
    <vdate>2021-09-30</vdate>
    <vtime>20:03:44</vtime>
  </Visit>
  <Visit tid="2" pid="200" vid="101">
    <vdate>2021-08-31</vdate>
    <vtime>21:03:44</vtime>
  </Visit>
  <Visit tid="3" pid="300" vid="102">
    <vdate>2022-01-01</vdate>
    <vtime>21:43:49</vtime>
  </Visit>
  <Visit tid="4" pid="400" vid="103">
    <vdate>2022-02-02</vdate>
    <vtime>11:43:49</vtime>
  </Visit>
  <Visit tid="5" pid="500" vid="101">
    <vdate>2022-02-03</vdate>
    <vtime>01:43:49</vtime>
  </Visit>
  <Visit tid="6" pid="500" vid="101">
    <vdate>2022-02-04</vdate>
    <vtime>03:43:49</vtime>
  </Visit>
  <Visit tid="7" pid="600" vid="102">
    <vdate>2022-03-04</vdate>
    <vtime>04:43:49</vtime>
  </Visit>
  <Visit tid="8" pid="600" vid="103">
    <vdate>2022-04-05</vdate>
    <vtime>05:43:49</vtime>
  </Visit>
  <Visit tid="9" pid="600" vid="102">
    <vdate>2022-05-03</vdate>
    <vtime>06:43:49</vtime>
  </Visit>
   <Visitor vid="101">
    <ip>165.11.33.45</ip>
  </Visitor>
  <Visitor vid="102">
    <ip>143.33.0.3</ip>
  </Visitor>
  <Visitor vid="103">
    <ip>146.33.0.3</ip>
  </Visitor>
</log>
